# Generated by Django 5.2 on 2025-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendationModel',
        ),
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recomendación de Productos', 'verbose_name_plural': 'Recomendaciones de Productos'},
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se generó la recomendación'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='input_products',
            field=models.JSONField(help_text='Lista de IDs de productos de entrada (formato JSON)'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommended_products',
            field=models.JSONField(help_text='Lista de IDs de productos recomendados (formato JSON)'),
        ),
    ]
